@OpalToolsTraining_HostAddress = https://localhost:7016

### Discovery Request

GET {{OpalToolsTraining_HostAddress}}/discovery
Accept: application/json

### Greeting Request

POST {{OpalToolsTraining_HostAddress}}/tools/user-greeter
Content-Type: application/json

{
  "parameters": {
    "Name": "John Doe"
  }
}

### Multiplication Request

POST {{OpalToolsTraining_HostAddress}}/tools/advanced-multiplier
Content-Type: application/json

{
  "parameters": {
    "ValueOne": 1.995,
    "ValueTwo": 93,
    "NumberOfPlaces": 3
  }
}

### Banana Tool

POST {{OpalToolsTraining_HostAddress}}/tools/banana-picture
Content-Type: application/json

{
  "parameters": {}
}

### Authenticated Tools Request (using random GUIDs)

POST {{OpalToolsTraining_HostAddress}}/tools/authentication-test
Content-Type: application/json

{
  "parameters": {
    "EmailAddress": "jo.bloggs@example.com"
  },
  "auth": {
    "provider": "OptiID",
    "credentials": {
      "token_type": "Bearer",
      "access_token": "<access-token-1446-chars>",
      "org_sso_id": "<id>",
      "cfg_client_id": "",
      "user_id": "00000000000000000000abcdef000001",
      "instance_id": "00000000000000000000abcdef000002",
      "customer_id": "00000000000000000000abcdef000003",
      "product_sku": "OPAL"
    }
  },
  "environment": {
    "execution_mode": "interactive"
  },
  "chat_metadata": {
    "thread_id": "00000000-0000-0000-0000-abcdef000005"
  }
}